name: deploy
on:
  # Deploys when main is updated
  push:
    branches: [main]

  # Allows manual trigger from Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Deploys landing page through a build hook"
        run: curl -X POST ${{ secrets.LANDING_PAGE_BUILD_HOOK }}
